# -*- coding: utf-8 -*-
"""projeto_santanderdevweek2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Wes-SNK/09d3272bf48343e7e0bcc23212a40f82/projeto_santanderdevweek2023.ipynb
"""

sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'

import pandas as pd

df = pd.read_csv('PROJETO_PIPELINE_ETL_USER_ID.csv')
user_ids = df['UserID'].tolist()
print(user_ids)

import requests
import json

def get_user(id):
  response = requests.get(f'{sdw2023_api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]
print(json.dumps(users, indent=4))

!pip install -U g4f

import g4f

def generate_news(user):
    response = g4f.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "Você é um administrador bancário com especialdiade em captação de clientes"
            },
            {
                "role": "user",
                "content": f"Crie uma mensagem personalizada para {user['name']} sobre a importância de se realizar investimentos inteligentes (no máximo 120 caracteres)"
            }
        ],
    )
    return response

for user in users:
   news = generate_news(user)
   print(news)

def update_user(user):
  response = requests.put(f"{sdw2023_api_url}/users/{user['id']}", json=user)
  return True if response.status_code == 200 else False

for user in users:
  success = update_user(user)
  print(f"User {user['name']} updated? {success}!")